singleTypes:
    # fetches only the most recently updated entry in a particular content type 
    # Generated file will be named after the fileName setting 
    - id: navigation
      directory: /src/content/navigation
      fileName: _nav
      fileExtension: json

repeatableTypes:
    # fetches all the entries of a content type and places them in a directory. 
    # Generated files will be named after their Entry ID in Contentful. 
    - id: blogPost
      directory: /src/content/posts/
      fileExtension: json
      mainContent: content